### ISSUE TITLE
Support extra large modal

### ISSUE THREAD

**Issue by sh977218** [ng-bootstrap/ng-bootstrap#1448]
Is there anyway I can make the modal extra large by 

     max-width:90%;
     width: 90%;

There should be flexible size of modal user can overwritten.

**Comment by sh977218** [comment]
I'm not sure if this is the correct way to do, but I got it working by:

    modalService.open(content,{windowClass:"hugeModal"});

style.css

     .hugeModal > .modal-dialog {
           max-width: 90% !important;
          width: 90% !important;
     }

**Comment by pkozlowski-opensource** [comment]
See https://github.com/ng-bootstrap/ng-bootstrap/issues/1309#issuecomment-279326043

tl;dr; is that you can either customize your Bootstrap CSS or add new CSS classes as you did. ng-bootstrap is prepared to work with custom sizes and there is nothing else to do in this library.

**Comment by Jimeh87** [comment]
Ran into issues with @sh977218 answer when centering modal and on a mobile device. If anyone else runs into that I would suggest doing something like this:
```css
@media (min-width: 768px) {
  .hugeModal > .modal-dialog {
    width: 90%;
    max-width: 1200px; /* or 90% or whatever */
  }
}
```

[credit](https://stackoverflow.com/a/25859829/3843101)
