### ISSUE TITLE
Cannot style disabled dates on hover in NgbDatepicker

### ISSUE THREAD

**Issue by Suroor-Ahmmad** [ng-bootstrap/ng-bootstrap#3638]
## Bug description:
Not able to apply on hover style to disabled dates. I was able to style the disabled dates, but `:hover` doesn't affect the datepicker.

Tried classes:
```
.custom-day.disabled:hover{
    background-color: gray !important;
}

.ngb-dp-day.disabled:hover{
    background-color: gray !important;
}
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.6

ng-bootstrap: ^5.1.1

Bootstrap: ^4.3.1

**Comment by peterblazejewicz** [comment]
@Suroor-Ahmmad
Can you provide a minimal sample of the problem using the stackblitz?
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/.github/ISSUE_TEMPLATE.md
It would help a ton!

**Comment by benouat** [comment]
You're definitely right, there is something weird about the way we style these cells, and how come we can't override them easily.

I'll have a deeper look for sure

**Comment by benouat** [comment]
I managed to do something with that piece of styles
```css
.ngb-dp-day.disabled:hover [ngbDatepickerDayView].outside {
    background-color: lime !important;
    color: blue !important;
    opacity: 1 !important;
}
```

but I find it super ugly, first because of the extra complexity of the selector, second because of the `!important` everywhere
