### ISSUE TITLE
Boostrap 5 support : Internet Explorer 11 issues

### ISSUE THREAD

**Issue by fbasso** [ng-bootstrap/ng-bootstrap#4064]
List of issues/display discrepancies noticed when using nbBootstrap with Internet Explorer 11:

- [ ] `.visually-hidden` doesn't work. The class does not even appear in the IE dev tools. Every dom element using this class is visually displayed 😃.
- [ ] The selects in the datepickers are badly rendered
- [ ] Not directly linked to the library, but it has impacts on some few sections in the demo: the row/col margins are not processed, as Bootstrap 5 uses css variables. For example:

``` css
.row {
    --bs-gutter-x: 1.5rem: ;
    --bs-gutter-y: 0: ;
    display: flex;
    flex-wrap: wrap;
    margin-top: calc(var(--bs-gutter-y) * -1);
    margin-right: calc(var(--bs-gutter-x) / -2);
    margin-left: calc(var(--bs-gutter-x) / -2);
}
```
