### ISSUE TITLE
Improved support for a responsive carousel component

### ISSUE THREAD

**Issue by charklewis** [ng-bootstrap/ng-bootstrap#4159]
### Feature Request

I have found a few examples where I would like to use this carrousel but hesitant too as it doesn't provide any way to dynamically change the number of active slides. It also doesn't look like it supports dynamic heights. Is there any upcoming work to address this?

I have tried a few variations on the below but it never seems to work. If I wrap the `ngbSlide` in a div, nothing renders.

```html
<ngb-carousel [interval]="0" [showNavigationIndicators]="false">
  <ng-template ngbSlide *ngFor="let product of productList">
    <app-product-card class="slider-item" [product]="product"></app-product-card>
  </ng-template>
</ngb-carousel>
```

```css
slider-item {
  width: 60%;

  @media (min-width: @content-width-sm) {
    width: 40%;
  }
  @media (min-width: @content-width-md) {
    width: 30%;
  }
  @media (min-width: @content-width-lg) {
    width: 25%;
  }
}
```
