### ISSUE TITLE
Apply css to tooltip

### ISSUE THREAD

**Issue by maritogaleano** [ng-bootstrap/ng-bootstrap#4375]
### Bug description:
I tried to apply css to the tooltip, however it is not applying, I did it directly like the example, however it does not accept me to inject on the existing selector

![image](https://user-images.githubusercontent.com/57814047/183926250-fd81b6a5-b71b-419f-ae72-29e1ee788b00.png)

I also tried to add the style directly, however it doesn't work either

![image](https://user-images.githubusercontent.com/57814047/183929396-20634605-98ce-4de5-b252-6bc65f8f4d8a.png)

![image](https://user-images.githubusercontent.com/57814047/183929201-dbe4bf3d-e807-4a0d-b028-9dccd4877020.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:   13.3.7

ng-bootstrap: 12.1.2

Bootstrap: 5.2.0-beta1

**Comment by jnizet** [comment]
The example in the documentation uses ViewEncapsulation.NONE. Yours doesn't. If you want to keep the default encapsulation, you need to add `::ng-deep ` before all your CSS selectors.

**Comment by maritogaleano** [comment]
> 

Should it look like this in my css selectors?

`.my-custom-class .tooltip-inner {
    background-color: darkgreen;
    font-size: 125%;
}

.my-custom-class.bs-tooltip-end .tooltip-arrow::ng-deep {
    border-right-color: darkgreen;
}

.my-custom-class.bs-tooltip-start .tooltip-arrow::ng-deep {
    border-left-color: darkgreen;
}

.my-custom-class.bs-tooltip-top .tooltip-arrow::ng-deep {
    border-top-color: darkgreen;
}`

**Comment by maxokorokov** [comment]
You can also apply a custom CSS class if it helps → https://ng-bootstrap.github.io/#/components/tooltip/examples#customclass

**Comment by jnizet** [comment]
@maritogaleano no. As I said, add `::ng-deep` **before** the css selectors:

https://stackblitz.com/edit/angular-jmvsej?file=src%2Fapp%2Ftooltip-customclass.ts

```css
    ::ng-deep .my-custom-class .tooltip-inner {
      background-color: darkgreen;
      font-size: 125%;
    }
    ::ng-deep .my-custom-class.bs-tooltip-end .tooltip-arrow::before {
      border-right-color: darkgreen;
    }
    ::ng-deep .my-custom-class.bs-tooltip-start .tooltip-arrow::before {
      border-left-color: darkgreen;
    }
    ::ng-deep .my-custom-class.bs-tooltip-top .tooltip-arrow::before {
      border-top-color: darkgreen;
    }
    ::ng-deep .my-custom-class.bs-tooltip-bottom .tooltip-arrow::before {
      border-bottom-color: darkgreen;
    } 
```
