### ISSUE TITLE
No animation for ng-bootstrap modal

### ISSUE THREAD

**Issue by makafsal** [ng-bootstrap/ng-bootstrap#894]
### Bug description:
   Bootstrap modal has no animation, in case of that facility is present in ng-bootstrap  I don't know how to use that. So please direct me to implement simple fadeIn and fadeOut animation for modal. Otherwise consider this as bug and please try to resolve as soon as possible...

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2

ng-bootstrap: alpha 8

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment]
We don't have animations support yet but tracking progress in #295 already.

**Comment by Eugeny** [comment]
A quick solution building up on the Bootstrap's builtin animation:

```scss
.modal {
    &.show .modal-dialog {
        transition: 0.25s all;
        opacity: 0;
        transform: translate(0, 5vh);
    }

    &.custom-show .modal-dialog {
        opacity: 1;
        transform: translate(0, 0);
    }
}

```

```javascript
import { Injectable } from '@angular/core'
import { NgbModal } from '@ng-bootstrap/ng-bootstrap'

@Injectable()
export class ModalService {
    constructor (private ngbModal: NgbModal) {}

    open (content: any, config?: any) {
        let modal = this.ngbModal.open(content, config)
        let instance = (modal as any)._windowCmptRef.instance
        setImmediate(() => {
            instance.windowClass = 'custom-show'
        })

        let fx = (modal as any)._removeModalElements.bind(modal);
        (modal as any)._removeModalElements = () => {
            instance.windowClass = ''
            setTimeout(fx, 250)
        }

        return modal
    }
}
```
